# Generated by Django 2.0.6 on 2018-07-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('biome_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('biome_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BiomeAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome_ID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegionAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_ID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='region_alias',
            field=models.ManyToManyField(to='plumes.RegionAlias'),
        ),
        migrations.AddField(
            model_name='biome',
            name='biome_alias',
            field=models.ManyToManyField(to='plumes.BiomeAlias'),
        ),
    ]
