# Generated by Django 2.0.6 on 2018-07-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, unique=True)),
                ('p_url', models.CharField(max_length=400)),
                ('p_date', models.DateTimeField()),
            ],
        ),
    ]
