# Generated by Django 2.0.6 on 2018-07-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0002_plume'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_num_hts',
            field=models.IntegerField(default=0),
        ),
    ]
