# Generated by Django 2.0.6 on 2018-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0003_plume_p_num_hts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_src_lat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_src_long',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
