# Generated by Django 2.0.6 on 2018-07-20 23:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0004_auto_20180720_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_long_rng',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), default=[0.0, 0.0], size=2),
        ),
    ]
