# Generated by Django 2.0.6 on 2018-07-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0008_auto_20180720_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_terr_max_ht',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_terr_mean_ht',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_terr_min_ht',
            field=models.IntegerField(default=0),
        ),
    ]
