# Generated by Django 2.0.6 on 2018-07-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0009_auto_20180720_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_dev_ht',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_fire_ht',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_local_var_ht',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_max_ht',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_med_ht',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_min_ht',
            field=models.IntegerField(default=0),
        ),
    ]
