# Generated by Django 2.0.6 on 2018-07-20 23:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0010_auto_20180720_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_dir',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_dir_vec',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=0, max_digits=6), null=True, size=2), null=True, size=2),
        ),
    ]
