# Generated by Django 2.0.6 on 2018-07-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0011_auto_20180720_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_wind_dir_diff',
            field=models.IntegerField(default=0),
        ),
    ]
