# Generated by Django 2.0.6 on 2018-07-20 23:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0012_plume_p_wind_dir_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plume',
            name='p_dir_vec',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=0, max_digits=6), default=[0.0, 0.0], size=2), null=True, size=2),
        ),
    ]
