# Generated by Django 2.0.6 on 2018-07-20 23:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0013_auto_20180720_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_avg_opt_depth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=[0.0, 0.0, 0.0, 0.0], size=4),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_avg_ss_albedo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=[0.0, 0.0, 0.0, 0.0], size=4),
        ),
    ]
