# Generated by Django 2.0.6 on 2018-07-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0014_auto_20180720_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='plume',
            name='p_avg_angstrom',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_avg_frp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_max_angstrom',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_max_frp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_num_fire_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plume',
            name='p_total_frp',
            field=models.IntegerField(default=0),
        ),
    ]
