# Generated by Django 2.0.6 on 2018-07-24 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumes', '0016_plume_p_clouds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plume',
            name='p_avg_angstrom',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_avg_frp',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_avg_opt_depth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=[0.0, 0.0, 0.0, 0.0], null=True, size=4),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_avg_ss_albedo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=[0.0, 0.0, 0.0, 0.0], null=True, size=4),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_dev_ht',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_local_var_ht',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_max_angstrom',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_max_frp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_max_ht',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_med_ht',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_min_ht',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_terr_mean_ht',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_total_frp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plume',
            name='p_wind_dir_diff',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
